name: CI

on: 
  push:
     branches: test_yml

jobs:
  windows:
    name: Build and test on windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64
      
      - name: install package
        run: pip install .        